install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
install.packages("corpustools")  
install.packages("igraph") 
install.packages("ggthemes") 
